---
  test: true
  broker:
      url:  http://localhost:15672
      username: guest
      password: guest
  analyzer:
    high-closure-rate-warning-threshold:  100
    high-creation-rate-warning-threshold: 100
    queue-high-flow-threshold:  100
    queue-low-flow-threshold: 20
    message-redelivery-coefficient: 0.50
    socket-usage-coefficient: 0.60
    runtime-process-usage-coefficient:  0.65
    file-descriptor-usage-warning-coefficient:  0.65
    consumer-utilization-warning-coefficient: 0.50
...